title: "Katungu Kivikwamo Malkia"
baseline: "Développeur Etudiant passionné"
description: "Développeur passionnée par la technologie, les projets innovants et le partage de connaissances."

params:
  author: "Katungu Kivikwamo Malkiag"
  github: "https://github.com/kivikwamo"
  email: "grace@example.com"
  social:
    - name: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/kivikwam"
    - name: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "#"
    - name: "Twitter"
      icon: "fab fa-twitter"
      url: "#"

menu:
  main:
    - name: "Accueil"
      url: "/"
      weight: 1
    - name: "Projets"
      url: "/projets/"
      weight: 2
    - name: "Blog"
      url: "/blog/"
      weight: 3
    - name: "Contact"
      url: "/contact/"
      weight: 4
